#!/bin/sh

# Check for proper versions of autotools
# We require:
#  - autoconf 2.50+
#  - automake 1.6+
#  - libtool 1.4+


## Using prereq in autoconf rather than here, mostly for the debian systems at
## this point

# clean up files which cause confusion when switch versions of auto*
rm -rf autom4te.cache

# Fire up autotools
libtoolize --force --copy && aclocal -I m4 $ACLOCAL_FLAGS && autoheader && automake --include-deps --add-missing --foreign --copy && autoconf 
